name: CI Pipeline for Todo App

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Bun manually
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # 3. Install dependencies
      - name: Install dependencies
        run: bun install

      # 4. TypeScript type check
      - name: TypeScript Check
        run: bun tsc --noEmit

      # 5. Lint code
      - name: Lint Code
        run: bun run lint

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Bun manually
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # 3. Install dependencies
      - name: Install dependencies
        run: bun install

      # 4. Build Next.js app
      - name: Build Next.js App
        run: bun run build
